// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2019-02-13 11:56:12.949657722 +0100 CET m=+0.000381120
package secrethub

// ClientVersion is the current version of the client
var ClientVersion string = "v0.18.0"
